print("hola mundo HOLA MUNDO")
print('Hola mundo 2')
print('Hola mundo 2')
print('Hola mundo 2')
print('Hola mundo 2')
print('Hola mundo 2')
print('Hola mundo 2')
print('Hola mundo 2')
print('Hola mundo 2')
print('Hola mundo 2')
print('Hola mundo 2')